Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> Thanks for the patch. What is the failure message that this fixes? I don't see ENABLE_WEBMTS in video_frame.cc, so I'm curious why you need cstdio.

The error message when building with emscripten with ENABLE_WEBMTS is:


libwebm/common/video_frame.cc:18:13: error: use of undeclared identifier 'stderr'


which is fixed by including cstdio. This is with the latest version of emscripten (1.38.28). Curiously there is no problem compiling with gcc-7 or clang-7 (emscripten is based on clang but I don't know what version).

As for ENABLE_WEBMTS, in the CMakeLists.txt file there is the following to explain why this option requires the file video_frame.cc:


set(webmts_sources
    ...
    "${LIBWEBM_SRC_DIR}/common/video_frame.cc"
    "${LIBWEBM_SRC_DIR}/common/video_frame.h"
    ...)

Patch-set: 2
Reviewer: Gerrit User 1332355 <1332355@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>